"""Grok — generator configuration.

This config is the single source of truth for Grok-specific parameters.
The agent populates it during Phase 1 (Generator Profiling), and all
scrapers/validators consume it via `--config configs/grok.py`.

Covers both Aurora and Grok Imagine models (same output characteristics).
Resolution reference: https://docs.x.ai/developers/model-capabilities/images/generation#aspect-ratio
"""

# === Generator identity ===
NAME = "grok"
DISPLAY_NAME = "Grok"

# === Image characteristics ===
EXPECTED_FORMATS = ["JPEG", "PNG"]
MIN_PIXELS = 800_000    # below = thumbnail or heavily downscaled
MAX_PIXELS = 5_000_000  # above = likely real upload (e.g., DSLR 14MP)

# JPEG quantization: Grok outputs very high quality (avg_q ≈ 1.0–5.8)
MAX_AVG_QUANTIZATION = 40.0  # Twitter recompresses to ~27-36; reject only severe compression

# Known aspect ratios from xAI API docs + observed via Twitter
KNOWN_ASPECT_RATIOS = [
    (1, 1),       # 1:1
    (16, 9),      # 16:9
    (9, 16),      # 9:16
    (4, 3),       # 4:3
    (3, 4),       # 3:4
    (3, 2),       # 3:2
    (2, 3),       # 2:3
    (2, 1),       # 2:1
    (1, 2),       # 1:2
    (11, 6),      # 11:6 — observed from @grok Twitter (1408x768, 2816x1536)
    (6, 11),      # 6:11
    (19.5, 9),    # 19.5:9
    (9, 19.5),    # 9:19.5
    (20, 9),      # 20:9
    (9, 20),      # 9:20
]
ASPECT_RATIO_TOLERANCE = 0.05  # 5% tolerance for rounding

# EXIF: presence of camera tags = NOT Grok output
CAMERA_EXIF_TAGS = [
    "Make", "Model", "ExposureTime", "FNumber",
    "ISOSpeedRatings", "FocalLength",
]

# === Scraping: Civitai ===
# On-site generation model versions (highest priority — very trustworthy)
# Each entry: (model_id, model_version_id)
# URL pattern: https://civitai.com/models/{model_id}?modelVersionId={model_version_id}
CIVITAI_MODEL_VERSIONS = [
    (2435474, 2738377),  # Grok — https://civitai.com/models/2435474?modelVersionId=2738377
]
# Tool ID fallback — only used if no model version IDs are set
CIVITAI_TOOL_ID = 284

# === Scraping: Reddit ===
REDDIT_SUBREDDITS = [
    "grok",
    "GrokAI",
    "GrokImagine",
]
REDDIT_SEARCH_QUERIES = [
    '"made with grok"',
    '"generated by grok"',
    '"grok generated this"',
    '"grok made this"',
    '"grok aurora"',
    '"grok imagine"',
    '"grok image generation"',
    '"created with grok"',
    '"grok AI art"',
    '"xAI image"',
    '"grok 2 image"',
    'flair:Imagine subreddit:grok',
]
REDDIT_AI_ART_FLAIRS = {"AI ART", "AI Art", "ai art", "Grok Art", "Image Generation"}

# --- Reddit post filtering ---
# Flairs that almost always indicate non-image content (skip these posts)
REDDIT_REJECT_FLAIRS = {
    # Discussion / meta
    "Discussion", "Question", "Help", "Meta", "Feedback",
    "Sub Meta", "Announcement", "Poll", "Rant", "Debate",
    "Bug", "Feature Request",
    # Meme / humor
    "Meme", "Humor", "Funny", "Shitpost", "Sloppost/Fard",
    # Advocacy / debate (not image showcases)
    "Defending AI", "Luddite Logic",
    # Non-image content
    "News", "Comparison", "Video", "AI TEXT", "AI Developments",
}

# Title keywords that indicate memes, comparisons, advocacy, screenshots
# (case-insensitive matching, checked as substrings)
REDDIT_REJECT_TITLE_KEYWORDS = [
    # Comparisons / benchmarks
    " vs ", " vs.", "versus", "comparison", "compared to", "better than",
    "benchmark", "ranking", "tier list", "side by side", "side-by-side",
    "before/after", "before and after",
    # Censorship / moderation drama
    "censored", "moderated", "content moderation", "censorship",
    "ban ", "banned", "jailbreak", "jailbroken", "loosen censorship",
    "bring back", "old grok", "uncensored",
    # Meme formats
    "pov:", "when you", "me when", "mfw", "mrw", "tfw",
    "unpopular opinion", "hot take", "am i the only",
    "change my mind",
    # Advocacy / meta
    "petition", "protest", "boycott",
    "goodbye", "rip ", " rip,",
    "update", "changelog", "release notes",
    # Other generators (comparison posts)
    "midjourney", "dall-e", "dalle", "stable diffusion",
    "seedream", "imagen", "ideogram", "flux",
    "chatgpt", "gemini image",
]

# Only download from these image hosting domains (skip external links)
REDDIT_ALLOWED_IMAGE_DOMAINS = {
    "i.redd.it",
    "preview.redd.it",
    "i.imgur.com",
}

# Skip self/text posts (discussion threads with no direct image)
REDDIT_SKIP_SELF_POSTS = True

# === Scraping: Twitter/X ===
TWITTER_BOT_USERNAME = "grok"
TWITTER_MEDIA_URL = "https://x.com/grok/media"
TWITTER_COOKIES_PATH = "data/cookies-x.txt"
# Search for user request tweets, then follow thread to find @grok's image reply
TWITTER_SEARCH_QUERIES = [
    "@grok generate",
    "@grok create",
    "@grok make",
    "@grok draw",
    "@grok can you generate",
    "@grok can you make",
    "@grok image of",
    "@grok picture of",
]

# === Safety / provenance ===
# Grok blocks exposed genitalia — images with these tags are NOT pure Grok output
BLOCKED_CONTENT_TAGS = [
    "penis", "vagina", "vulva", "genitals", "testicle",
    "labia", "clitoris", "phallus",
]

# === Content classification (JoyCaption / VLM) ===
#
# REJECT_KEYWORDS: always reject if found in caption (unambiguous non-image content)
# TEXT_PAIRED_KEYWORDS: only reject when co-occurring with TEXT_INDICATORS
#   (e.g. "table" alone = AI image of furniture; "table" + "spreadsheet" = data table)
#
# Matched with word boundaries (\b) to avoid "graph" matching "photograph".

REJECT_KEYWORDS = [
    # Screenshots / UI — unambiguously non-image
    "screenshot", "user interface", "app interface", "chat interface",
    "settings page", "settings menu", "status bar",
    "navigation bar", "toolbar", "menu bar", "dialog box",
    "browser window", "browser tab", "address bar", "url bar",
    "home screen", "lock screen",
    "file manager", "task manager", "control panel",
    # Social media UI
    "tweet", "retweet", "like button", "follow button",
    "comment section", "social media post",
    "verified badge", "instagram post", "tiktok",
    "facebook post", "reddit post",
    # Memes / text overlay
    "meme", "impact font", "text overlay",
    "top text", "bottom text", "demotivational",
    "reaction image", "rage comic",
    # Technical / error
    "error message", "error screen", "loading screen",
    "code snippet", "terminal", "command line",
    "source code", "stack trace",
    "api response", "json output", "xml output",
    # Unambiguous data/document content
    "spreadsheet", "powerpoint", "presentation slide",
]

# These keywords are ambiguous — "table" could be furniture, "conversation"
# could be people talking in a scene. Only reject when paired with text
# indicators that confirm it's text-heavy / non-photographic content.
TEXT_PAIRED_KEYWORDS = [
    "table", "chart", "bar chart", "pie chart", "histogram",
    "scatter plot", "flow chart", "org chart", "gantt chart",
    "conversation", "chat bubble", "chat message", "text message",
    "notification", "login", "sign in", "sign up",
    "before and after", "side by side", "comparison",
    "collage", "grid of images", "photo grid",
    "infographic", "diagram", "schematic",
    "document", "receipt", "invoice", "certificate",
    "floor plan", "blueprint",
]

# When any of these appear alongside TEXT_PAIRED_KEYWORDS, reject the image.
TEXT_INDICATORS = [
    "text", "font", "typed", "written", "caption",
    "heading", "title", "label", "header",
    "paragraph", "sentence", "words",
    "data", "numbers", "rows", "columns",
    "cells", "grid", "spreadsheet",
    "screenshot", "user interface", "browser",
]

# === Scraping: Grok Imagine (grok.com/imagine) ===
# Public gallery — 100% Grok-generated, perfect provenance.
# Discovery via Brave Search, download from xAI CDN.
GROK_IMAGINE_SEARCH_DELAY = (2.0, 5.0)  # Brave Search rate limit
GROK_IMAGINE_POST_DELAY = (1.0, 3.0)    # post page + CDN download

# === Rate limiting ===
REQUEST_DELAY = (1.0, 5.0)       # general delay between requests
CIVITAI_API_DELAY = (5.0, 12.0)  # Civitai is aggressive with 429s
CIVITAI_DOWNLOAD_DELAY = (1.0, 3.0)
TWITTER_SEARCH_DELAY = (3.0, 8.0)  # conservative for account safety
